theme: jekyll-theme-minimal
title: My github pages with jekyll
author: Piece of sea
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just a little description

# social links
twitter_username: miss
github_username:  miss

show_excerpts: true # set to false to remove excerpts on the homepage
